### ISSUE TITLE
Suggestion : JSDuck strategy

### ISSUE THREAD

**Issue by cfmitrah** [Ortus-Solutions/DocBox#4]
https://github.com/murrah/ColdDuck

**Comment by lmajano** [comment]
So are you suggesting we build it, or are you suggesting that you build it :)

**Comment by cfmitrah** [comment]
Somebody (@murrah) already built it, need to integrate it into DocBox.  If time permits, I will try to do that. It might be a good addition to DocBox.

**Comment by bdw429s** [comment]
Bring on the pull requests!

**Comment by murrah** [comment]
I haven't really used or looked at ColdDuck since I wrote it. I am sure it could be improved! :-)

**Comment by lmajano** [comment]
Will be closing issues here and moving to our Jira instance:
https://ortussolutions.atlassian.net/projects/DOCBOX
